version: '3.8'

services:
  web:
    build: .
    container_name: yveks_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - yveks_network

  db:
    image: mysql:8.0
    container_name: yveks_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dreva
      MYSQL_USER: usuario
      MYSQL_PASSWORD: clave
    volumes:
      - db_data:/var/lib/mysql
      - ./BD/intercambio.sql:/docker-entrypoint-initdb.d/01-intercambio.sql
      - ./BD/seed_intercambio.sql:/docker-entrypoint-initdb.d/02-seed_intercambio.sql
    networks:
      - yveks_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: yveks_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - yveks_network

volumes:
  db_data:

networks:
  yveks_network:
    driver: bridge
